DOI-USGS/dataretrieval-python

.github/workflows/python-package.yml
.gitignore
requirements-dev.txt

As Python 3.10 is now the current version of Python, I think it makes sense to update the continuous integration workflow to include recent versions such as 3.9 and 3.10 (especially as the deployment to pypi uses the latest version of Python). While editing the workflow `.yml` I thought it might be reasonable to also test other OS beyond Ubuntu as GitHub Actions supports MacOS and Windows as well. While running the tests, we can also generate test coverage and have it print to the Actions console in the event one ever wants to see what is being covered and what isn't. As GitHub Actions on public repositories is currently not subject to any quotas or limits, I also removed the restriction which only ran the CI workflow when pushing or pulling to the "master" branch. Seems like it could …

Broaden Continuous Integration Workflow

---

dataretrieval/nwis.py
tests/nwis_test.py

While I was reviewing the code for something else I noticed a `dropna` call that didn't have `inplace` set to True and wasn't getting assigned to a new variable. I set inplace to True as it seemed that was what was being done elsewhere in the code. If you prefer the dropna to be removed then I can make that edit instead.

Add inplace Argument to dropna

---

.github/workflows/python-package.yml
dataretrieval/nwis.py

- adds deprecation warnings to calls to the qwdata service as well as a warning in the documentation
- drops CI support for python 3.6 as it is no longer included in the "ubuntu-latest" image (hence the failing CI build)
@lstanish-usgs this is the extent of where we would place warnings for this deprecation - feel free to propose changes to the wording.

warnings for qwdata deprecation

---

dataretrieval/nwis.py
dataretrieval/utils.py
setup.py
tests/nwis_test.py
tests/waterservices_test.py

This PR is designed to close #47.
**This PR does not change current default functionality**
The gist of the problem (as I understood it) is that some groundwater data records lack full date-time information. Sometimes the timestamp is missing, or even the month or day is not provided. The current approach to creating `pandas` datetime objects assumes all of that information is known, and if not, creates the equivalent of a `NaN` entry (`NaT`). This is fundamentally a conservative solution, as no datetime information is provided when it is incomplete; the user can always look at the original columns (`lev_dt`, `lev_tm`, `lev_tz_cd`) if they wanted to dig into the available partial data or construct their own index/ordering for the data frame. *The existing implementation could be the final …

add ability to coerce incomplete datetime info + tests

---

dataretrieval/utils.py
tests/utils_test.py

This PR closes #64. 
It is pretty straightforward, we handle the 414 response case in `query()` and print out a custom error message to convey to the user that the API query generated by their function call is too long. Previous error message was not useful to the end-user, per #64.
This PR also adds a corresponding unit test which checks that both the expected error type and message are captured when trying to perform a query with a URL that is too long.

Better 414 Response Error Message

---

dataretrieval/codes/states.py
dataretrieval/nwis.py
docs/source/examples/index.rst
docs/source/examples/siteinfo_examples.rst
docs/source/meta/contributing.rst
tests/nwis_test.py

This PR closes #34.
Now in `get_info` the `kwargs` are checked for the `seriesCatalogOutput` parameter which, if true, is set in `kwargs` and the expanded rdb output is not requested. If `seriesCatalogOutput` is false or not present, then the expanded rdb output is requested -- so the default behavior of this function does not change.
Tests and an example in the documentation are added to show how this argument works.
Additional details surrounding the original problem are described in #34. 
A section in the documentation is added on updating the version numbers, which was prompted by #66 which still needs to be resolved.

Fix to enable seriesCatalogOutput

---

dataretrieval/nwis.py
tests/nwis_test.py

Looking into issue #26 revealed that recent changes to the datetime handling missed the case when the data frame is empty, instead a non-intuitive error message was delivered:
```
>>> df = nwis.get_record(sites='011277906', service='iv', start='2010-07-20', end='2010-07-20')
Traceback (most recent call last):
File "/Users/jhariharan/mambaforge/envs/dataretrieval/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
return self._engine.get_loc(casted_key)
File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
File …
```

Skip datetime handling for empty data frames

---

dataretrieval/nwis.py
tests/nwis_test.py
tests/waterservices_test.py

This PR closes #73 and fixes bug with `countyCd` queries.
---
Specifically the following changes are proposed:
- Allows water service queries (`query_waterservices`) to be called with only the `countyCd` being specified, previously this was not allowed and made it impossible? to do a county query. Alters error message to match expanded behavior.
- Expands the `_set_metadata` function to allow the `lambda` function assigned to the `site_info` attribute of the metadata object to be set by parameters other than only `sites` and `site_no`
- Adds tests of this expanded `_set_metadata` functionality that do not execute any queries but check that the `lambda` functions behind `metadata.site_info` are set up
- Relaxes metadata check for `site_info` in `waterservices_test.py` as the `site_info` …

Expand site info metadata (addresses #73)

---

dataretrieval/nadp.py
docs/source/userguide/index.rst

fixes 2 things that seem wrong with the documentation
1. `nadp.py` API reference was not rendering because it was not possible for the CI runner to import `gdal` we work around this by returning a warning and then mocking the library if importing fails, this should allow docs to render
2. the new "data portals" documentation page was only accessible via a link from the main documentation page, now it has been added to the "user guide" section so it can be navigated to

minor fixes for docs

---

.github/workflows/python-package.yml
.gitignore
dataretrieval/__init__.py
dataretrieval/utils.py
docs/source/conf.py
pyproject.toml
tests/utils_test.py

Aims to close #83 by adding a string to the header in our HTTP GET requests that identifies the python dataretrieval package and version making the request.
Checked functionality against what the R package does and this follows that convention. The "user-agent" information sent to the server is `python-dataretrieval/<version>` which is consistent with the approach in R.
Wrote some tests for this logic.
---
@thodson-usgs can you confirm that my syntax for getting the current version is correct? We don't currently have a `_version.py` file so in the interest of having the code be more resilient there's currently try-except logic to substitute "version-unknown" when it is not available. But I am hoping that once we do the next release the code `dataretrieval.__version__` will successfully …

Defining a user-agent in GET requests

---

dataretrieval/nwis.py

Before:
After:
https://github.com/DOI-USGS/dataretrieval-python/issues/97

Type hint for DataFrame

---

dataretrieval/nwis.py
dataretrieval/utils.py
dataretrieval/wqp.py

From #100 - adds an optional boolean parameter `ssl_check` to functions that gets passed through the `requests.get()` to enable skipping of the SSL certificate check. Default value is `True` which checks the SSL certificate (and is the recommended behavior).

add ssl_check optional parameter

---

dataretrieval/nwis.py
tests/waterservices_test.py

This is an initial implementation of adding type hints that includes type hints just for one function of `nwis` module. If this looks good, I can implement the same for the rest of the functions of the `nwis `module.

[#116] initial implementation of type hints

---

dataretrieval/nwis.py
dataretrieval/utils.py

Some sites use a method code of 'x', which was breaking the json parser, which interpret '_x' as a duplicate column following pandas `merge` convention.
This fix removes `update_merge()` entirely (I might regret this 💣 💥) and adds the functionality into the json parser itself. If nothing else, this should improve performance.

129 data downloading issue with a specific gauging station

---

dataretrieval/nwis.py
dataretrieval/wqp.py

This MR adds warnings to `nwis.get_qwdata` and `nwis.get_info` when `seriesCatalogOutput=True` about the impending lack of updates to the qw service. Please review for accuracy in content and that the location and warning specifications are sufficient within the functions. Thanks!

Add warning message for qw data queries

---

dataretrieval/nldi.py

Set CRS to "EPSG:4326" for GeoDataFrame objects that are returned to the user

update(nldi.py): Add CRS information to GeoDataFame objects

---

code.json

To make the official release public again, we need to go through the Software Management official release process checklist. I believe we can use most of the info @thodson-usgs provided in [2023](https://code.chs.usgs.gov/software/software-management/-/issues/936), but @ldecicco-USGS noticed that the code.json file still contains the outdated repo info. I have updated it in this PR. Once merged with `master`, I will sync it with GitLab and then make the exact same change to the tagged official release (v1.0.2). Does that sound good?
One question: should we change the metadataLastUpdated (line 42) date in the code.json file?

Adjust code.json to point to new repo location

---

README.md

Added a couple of sentences about the change to the `gwlevels` service in an attempt to catch/inform users that they need to update their version to leverage the new service.

Add info about gwlevels service

---

.github/workflows/python-package.yml
.github/workflows/python-publish.yml
.github/workflows/sphinx-docs.yml

There is a potential security risk where the maintainer of a GitHub Action could retroactively change the code associated with specific, tagged versions of the action (e.g., v1, v2). Laura DeCicco proposed an alternative to replace version numbers in GitHub Action yml files with the specific commit hashes associated with those release versions, which are immutable.
This PR makes those changes for the seven instances where an external action is invoked. I couldn't identify the exact version for some of the actions (e.g., there are multiple v2.#.# versions for the checkout action), so I just selected the hashes associated with the most recently released version for each action.

Update GH action tags to most recent release commit hashes

---

dataretrieval/nwis.py

BREAKING CHANGE: [v1.0.10](https://github.com/DOI-USGS/dataretrieval-python/releases/tag/v1.0.10) is the only affected version. See footer for more detail.
The nwis site service (and the USGS more broadly) uses the NAD83 crs.
64a575d introduced a bug that hard coded the nwis module's crs to EPSG:4236 -- Hu Tzu Shan 1950 (https://epsg.io/4236). I guarantee 64a575d meant to hard code _EPSG:4326_ -- WGS84. It appears it was fat fingered and missed in #143's PR review (it happens to the best of us:)).
Bug reproduction:
```python
import dataretrieval
from dataretrieval import nwis
assert dataretrieval.__version__ == "1.0.10"
df, metadata = nwis.get_info(sites="01013500")
assert df.crs.to_epsg() == 4236
```
In either case, EPSG:4326 is still _technically_ the wrong crs. For example: …

fix!: correct `nwis` module GeoDataFrames crs to EPSG:4269 (NAD 83)

---

dataretrieval/nwis.py
tests/nwis_test.py

This small PR adds a filtering step to the `get_gwlevels` function that ensures only the requested pcodes are returned. For whatever reason, the "new" gwlevels endpoint doesn't seem to recognize the `parameterCd` argument, even though it is still specified in the documentation: https://nwis.waterservices.usgs.gov/docs/groundwater-levels/groundwater-levels-details/
See Issue #179

Fix gwlevels pcode
